<template>
  <v-app>
    <v-container class="privacy">
      <h2 class="pt-5">Privacy Policy</h2>
      <div>Pic Translator has established the following privacy policy regarding the handling of users' personal information for the services provided on this website.</div>
      <h3 class="pt-5">Disclaimer</h3>
      <div>Transcription and translation are automatically generated by our API. Use them at your own discretion and at your own risk. This website is not responsible for the content of the transcripts and translations. Please be aware of this before using the service on this site.</div>
      <div>We cannot be held responsible for any problems or issues that may arise from the use of this website or the use of transcription and translation services. We cannot be held responsible for any problems that may arise from the use of this site.</div>
      <h3 class="pt-5">About the access analysis tools used on this site</h3>
      <div>This site uses Google Analytics, an access analysis tool by Google. This service uses cookies to collect traffic data. The traffic data is collected anonymously and does not identify any individual. You can disable this feature by disabling cookies, so please check your browser's settings. For more information on this agreement, please click <a href="https://policies.google.com/terms?hl=en">here</a>.</div>
      <h3 class="pt-5">Privacy Policy for Advertising</h3>
      <div>This site may use third-party advertising services (such as Google AdSense) in the future. This service may use cookies (but not your name, address, email address, or phone number) to display advertisements for products and services that may be of interest to you, as well as information about your access to this site and other sites. </div>
    </v-container>
  </v-app>
</template>
<style scoped>
.privacy {
  color:#535353;
  line-height: 2;
}
</style>